apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-statefulset
spec:
  serviceName: {{ .Chart.Name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      system: database
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        system: database
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.statefulset.containers.image.repository }}:{{ .Values.statefulset.containers.image.tag }}
        imagePullPolicy: {{ .Values.statefulset.containers.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.statefulset.containers.containerPort }}
        env:
        - name: MSSQL_PID
          value: {{ .Values.statefulset.containers.env.MSSQL_PID | quote }}
        - name: ACCEPT_EULA
          value: {{ .Values.statefulset.containers.env.ACCEPT_EULA | quote }}
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-secret
              key: password
        volumeMounts:
        - name: {{ .Chart.Name }}-storage
          mountPath: /var/opt/mssql
      volumes:
        - name: {{ .Chart.Name }}-storage
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-pv-claim