apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-app-config
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Error",
          "System": "Error",
          "Microsoft": "Error"
        }
      }
    }