apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: arch.homework
    http:
      paths:
        - path: /otusapp/IgorLopushko(/|$)(.*)
          backend:
            serviceName: {{ .Chart.Name }}-app
            servicePort: {{ .Values.service.targetPort }}