apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-app
spec:
  selector:
    app: {{ .Chart.Name }}-app
    system: backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}