apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: -.kubernetes
build:
  artifacts:
  - image: drmoz/userservice
    context: solution
    docker:
      dockerfile: UserService.Dockerfile
deploy:
  kubectl:
    manifests:
    # create configmaps and secrets
    - user-svc-app.configmap.yaml
    - user-svc-app.appsettings.secret.yaml
    - user-svc-mssqldb.secret.yaml

    # create pv claims
    - user-svc-mssqldb.pvclaim.yaml
    
    - user-svc-app.deployment.yaml    
    - user-svc-mssqldb.statefulset.yaml

    #setup services
    - user-svc-app.service.yaml
    - user-svc-mssqldb.service.yaml

    #setup ingresses
    - user-svc-app.ingress.yaml