apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-svc-app-replicas
spec:
  replicas: 3
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: user-svc-app
      system: backend
  template:
    metadata:
      labels:
          app: user-svc-app
          system: backend
    spec:
      containers:
      - name: user-svc-app
        image: drmoz/userservice:v1
        ports:
          - containerPort: 80

        # to know when to restart a container
        livenessProbe:
          httpGet:
            port: 80
            path: /health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2

        # to know when a container application has started
        readinessProbe:
          httpGet:
            port: 80
            path: /health
          initialDelaySeconds: 10
          periodSeconds: 5

        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Kubernetes"
        
        # mounts configmap and secret volumes to container
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
        - name: secret-volume
          mountPath: /app/secret
          readOnly: true

      # mounts configmap and secret volumes to pod
      volumes:
      - name: config-volume
        configMap:
          name: user-svc-app-config
      - name: secret-volume
        secret:
          secretName: user-svc-app-secret