apiVersion: v1
kind: Secret
metadata:
  name: user-svc-app-secret
data:
  appsettings.secret.json: ewogICAgIkNvbm5lY3Rpb25TdHJpbmdzIjogewogICAgICAgICJVc2VyQ29udGV4dCI6ICJTZXJ2ZXI9MTkyLjE2OC45OS4xMDUsMzE0MzM7RGF0YWJhc2U9VXNlcnM7VXNlciBJZD1TQTtQYXNzd29yZD1BZG1pbi0xMjM7IgogICAgfQp9
type: Opaque