apiVersion: v1
kind: Service
metadata:
  name: user-svc-mssqldb
spec:
  selector:
    app: user-svc-mssqldb
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 31433
  type: NodePort