# Default values for user-svc-mssql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
appName: "user-svc"

replicaCount: 1

statefulset:
  containers:
    image:
      repository: mcr.microsoft.com/mssql/server
      pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      tag: 2019-latest
    containerPort: 1433
    env:
      MSSQL_PID: "Developer"
      ACCEPT_EULA: "Y"

job:
  containers:
    image:
      repository: drmoz/userservice-migrations
      pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      tag: v1

service:
  type: ClusterIP
  port: 1433
  targetPort: 1433
  nodePort: 31433

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
